name: Browserstack Test

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  execute_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write   
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}" >> .env
          echo "BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}" >> .env
          echo "GH_ACTIONS_RUNNER=${{ github.run_number }}" >> .env

      - uses: actions/setup-python@v3
        with:
          python-version: 3.12


      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Execute Tests
        id: execute_test
        run: robot -d ./reports -x ./reports/report.html -v EMULATOR:browserstack -v PLATFORM_NAME:android -i regressivo .
        continue-on-error: true

      - name: Execute Flaky Tests
        if: steps.execute_test.outcome != 'success'
        run: |
          robot -d ./reports --rerunfailed ./reports/output.xml --output rerun.xml .
        continue-on-error: true

      - name: Merge Test Reports
        if: steps.execute_test.outcome != 'success'
        run: |
          rebot -d ./reports --merge ./reports/output.xml ./reports/rerun.xml

          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: reports

  generate_report:
    if: always()
    needs: [execute_test]   
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: reports

      - name: Implantar Resultados no Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "**/reports/"

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.4
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.sha }}
          pull_request_id: ${{ github.event.number }}
 